### ISSUE TITLE
Display mismatched values in equality checks

### ISSUE THREAD

**Issue by furkanusta** [svunit/svunit#171]
This is already present for string comparisons, it would be nice to have something similar for `FAIL_IF_EQUAL` and `FAIL_UNLESS_EQUAL` as well. 
I am aware that it is not possible to satisfy everyone when it comes to formatting (hex vs decimal etc) , but for me anything would be better than nothing.

**Comment by tudortimi** [comment]
I'm guessing it would also be possible to use `%p` as a default format specifier, but give the user the possibility to pass a custom format specifier (e.g. `%x`).

**Comment by tudortimi** [comment]
I have to think a bit whether adding prints ruins backwards compatibility. I'm guessing that it won't bust anything if `%p` is used as a default format, but I need to experiment a bit.

**Comment by tudortimi** [comment]
Seems to work fine, at least in Xcelium and QuestaSim, but I'm not expecting problems in other tools. I'm thinking of something along the lines of:

```
// foo = 1
// bar = 2
`FAIL_UNLESS_EQUAL(foo, bar)

// prints:
fail_if_equal: (foo) === (bar)
foo = 1
bar = 2
```

Also, I think it would be possible to let the user specify the format to use when printing:

```
// foo = 'hdead;
// bar = 'hbeef;
`FAIL_UNLESS_EQUAL(foo, bar, "%x")

// prints:
fail_if_equal: (foo) === (bar)
foo = 'hdead
bar = 'hbeef
```

**Comment by tudortimi** [comment]
So this actually can't work, in any case not with the features supported by current simulators. It seems that #173 implements this, but it inserts a very subtle bug:

```
int i = 0; 
`FAIL_IF_EQUAL(i++, 0) 
```

This test should fail, because `i` should still be `0` for the comparison. It won't fail, because `i` will already be `1` when compared, due to the fact that `i++` is already executed when determining what the should be printed for the left hand side in case of a fail.

There is no way of storing the value of `i++` without knowing its type. It's also not possible to infer its type.
