### ISSUE TITLE
perl shebang

### ISSUE THREAD

**Issue by jasonparsons** [svunit/svunit#38]
scripts should use #!/usr/bin/env perl
so they are not dependent on /usr/bin/perl being there

**Comment by GrueMaster** [comment]
This actually applies to all scripts, not just perl.  For example, the bash scripts.  On Redhat/Centos /usr/bin/bash is fine, but on Debian/Ubuntu distros, this is /bin/bash.  /usr/bin/env <shell> is the LSB prescribed method for getting the correct shell.

Also, on Ubuntu (and some others), you need to specify bash instead of just using sh, as they use dash as a replacement for minimal overhead during booting and within busybox.  (Note: this is just for reference).
